#!/usr/bin/env python3
"""
Generate a SystemVerilog config module from a YAML register map.

Usage:
    python3 gen_cfg.py <input.yaml> [output.sv]

Register types:
    RW      read-write, internal register, output port per field
    WO      write-only, internal register, output port per field, read returns 0
    RO      read-only, driven by external input port (src field required)
    RC      read-clear, sticky-OR input into internal reg, cleared on read
    W1C     write-1-clear, sticky-OR src into internal reg, cleared by writing 1
    INT     read-clear pending (sticky-OR src) + paired RW enable @ enable_addr,
            outputs irq = |(pending & enable)  (port name = 'irq' or {name}_irq)
    RO_CNT  read-only counter, increments on src pulse (src = inc signal name)
    RC_CNT  read-clear counter, increments on src pulse, cleared on read
"""

import sys
import yaml
from pathlib import Path


def parse_bits(bits_str):
    s = str(bits_str).strip()
    if ':' in s:
        hi, lo = map(int, s.split(':'))
    else:
        hi = lo = int(s)
    return hi, lo, hi - lo + 1


def logic_decl(width):
    return 'logic' if width == 1 else f'logic [{width-1}:0]'


def reset_literal(width, value):
    return f"1'b{value}" if width == 1 else f"{width}'d{value}"


def src_width(reg):
    return max(parse_bits(f['bits'])[0] for f in reg['fields']) + 1


def irq_name(reg):
    return reg.get('irq', f"{reg['name'].lower()}_irq")


def build_rdata_expr(fields, data_w):
    parsed = sorted(
        [(*parse_bits(f['bits']), f['name']) for f in fields],
        key=lambda x: x[0],
        reverse=True,
    )
    parts = []
    cur = data_w - 1
    for hi, lo, _, name in parsed:
        if cur > hi:
            parts.append(f"{cur - hi}'b0")
        parts.append(f'{name}_reg')
        cur = lo - 1
    if cur >= 0:
        parts.append(f"{cur + 1}'b0")
    return ('{' + ', '.join(parts) + '}') if len(parts) > 1 else parts[0]


def padded_src_expr(expr, sw, data_w):
    if sw < data_w:
        return f"{{{data_w - sw}'b0, {expr}}}"
    return expr


def generate(cfg):
    module = cfg['module']
    addr_w = cfg['addr_w']
    data_w = cfg['data_w']
    regs   = cfg['registers']

    L = []

    def ln(s=''):
        L.append(s)

    for r in regs:
        if r['type'] in ('RO', 'RC', 'RO_CNT', 'RC_CNT', 'W1C', 'INT') and 'src' not in r:
            sys.exit(f"Error: register '{r['name']}' (type={r['type']}) requires a 'src' field")
        if r['type'] == 'INT' and 'enable_addr' not in r:
            sys.exit(f"Error: register '{r['name']}' (type=INT) requires an 'enable_addr' field")
        if r['type'] in ('RAM_RW', 'RAM_RO', 'RAM_WO') and ('alen' not in r or 'dlen' not in r):
            sys.exit(f"Error: register '{r['name']}' (type={r['type']}) requires 'alen' and 'dlen' fields")

    RAM_TYPES  = {'RAM_RW', 'RAM_RO', 'RAM_WO'}
    RAM_WRITES = {'RAM_RW', 'RAM_WO'}   # generate wdata / wen
    RAM_READS  = {'RAM_RW', 'RAM_RO'}   # generate rdata / ren, appear in read mux

    rw_wo_regs   = [r for r in regs if r['type'] in ('RW', 'WO')]
    ro_rc_regs   = [r for r in regs if r['type'] in ('RO', 'RC')]
    rc_regs      = [r for r in regs if r['type'] == 'RC']
    w1c_regs     = [r for r in regs if r['type'] == 'W1C']
    int_regs     = [r for r in regs if r['type'] == 'INT']
    cnt_regs     = [r for r in regs if r['type'] in ('RO_CNT', 'RC_CNT')]
    ram_regs     = [r for r in regs if r['type'] in RAM_TYPES]
    non_ram_regs = [r for r in regs if r['type'] not in RAM_TYPES]
    rw_wo_fields = [(r, f, *parse_bits(f['bits'])) for r in rw_wo_regs for f in r['fields']]

    # --- header ---
    ln(f'// {module} — generated by gen_cfg.py')
    ln()
    ln(f'module {module} #(')
    ln(f'    parameter int ADDR_W = {addr_w},')
    ln(f'    parameter int DATA_W = {data_w}')
    ln(') (')
    ln('    input  logic                clk,')
    ln('    input  logic                rst_n,')
    ln()
    ln('    input  logic                sab_valid,')
    ln('    input  logic                sab_wen,')
    ln('    input  logic [ADDR_W-1:0]   sab_addr,')
    ln('    input  logic [DATA_W-1:0]   sab_wdata,')
    ln('    output logic                sab_ready,')
    ln('    output logic [DATA_W-1:0]   sab_rdata,')
    ln()

    seen_ports = set()
    extra_ports = []

    def add_port(direction, typ, name):
        if name not in seen_ports:
            seen_ports.add(name)
            extra_ports.append((direction, typ, name))

    for r, f, hi, lo, w in rw_wo_fields:
        add_port('output', logic_decl(w), f['name'])
    for r in ro_rc_regs:
        add_port('input ', logic_decl(src_width(r)), r['src'])
    for r in w1c_regs:
        add_port('input ', logic_decl(src_width(r)), r['src'])
    for r in int_regs:
        add_port('input ', logic_decl(src_width(r)), r['src'])
        add_port('output', 'logic', irq_name(r))
    for r in cnt_regs:
        add_port('input ', 'logic', r['src'])
    for r in ram_regs:
        name = r['name'].lower()
        if r['alen'] > 0:
            add_port('output', logic_decl(r['alen']), f'{name}_addr')
        if r['type'] in RAM_WRITES:
            add_port('output', logic_decl(r['dlen']), f'{name}_wdata')
            add_port('output', 'logic',               f'{name}_wen')
        if r['type'] in RAM_READS:
            add_port('input ', logic_decl(r['dlen']), f'{name}_rdata')
            add_port('output', 'logic',               f'{name}_ren')

    for i, (direction, typ, name) in enumerate(extra_ports):
        comma = ',' if i < len(extra_ports) - 1 else ''
        ln(f'    {direction} {typ:<20} {name}{comma}')

    ln(');')
    ln()

    # --- localparams ---
    for r in regs:
        addr_val = r['addr']
        ln(f"    localparam logic [ADDR_W-1:0] ADDR_{r['name']:<10} = {addr_w}'h{addr_val:x};")
    for r in int_regs:
        en_name = r['name'] + '_EN'
        ln(f"    localparam logic [ADDR_W-1:0] ADDR_{en_name:<10} = {addr_w}'h{r['enable_addr']:x};")
    ln()

    # --- internal signals ---
    for r, f, hi, lo, w in rw_wo_fields:
        ln(f'    {logic_decl(w)} {f["name"]}_reg;')
    for r in rc_regs:
        ln(f'    {logic_decl(src_width(r))} {r["name"].lower()}_rc_reg;')
    for r in w1c_regs:
        ln(f'    {logic_decl(src_width(r))} {r["name"].lower()}_w1c_reg;')
    for r in int_regs:
        ln(f'    {logic_decl(src_width(r))} {r["name"].lower()}_int_reg;')
        ln(f'    {logic_decl(src_width(r))} {r["name"].lower()}_en_reg;')
    for r in cnt_regs:
        ln(f'    {logic_decl(src_width(r))} {r["name"].lower()}_reg;')
    for r in ram_regs:
        ln(f'    logic {r["name"].lower()}_sel;')
    ln()

    # --- assigns ---
    ln('    logic sab_valid_d;')
    ln('    logic vld_pos_edge;')
    ln()
    ln('    always_ff @(posedge clk or negedge rst_n) begin')
    ln("        if (!rst_n) begin")
    ln("            sab_valid_d <= 1'b0;")
    ln('        end else begin')
    ln('            sab_valid_d <= sab_valid;')
    ln('        end')
    ln('    end')
    ln()
    ln('    always_ff @(posedge clk or negedge rst_n) begin')
    ln("        if (!rst_n) begin")
    ln("            sab_ready <= 1'b0;")
    ln('        end else begin')
    ln('            sab_ready <= vld_pos_edge;')
    ln('        end')
    ln('    end')
    ln()
    ln('    assign vld_pos_edge = sab_valid & ~sab_valid_d;')
    ln()
    for r, f, hi, lo, w in rw_wo_fields:
        ln(f'    assign {f["name"]} = {f["name"]}_reg;')
    if rw_wo_fields:
        ln()

    for r in int_regs:
        nm = r['name'].lower()
        ln(f'    assign {irq_name(r)} = |({nm}_int_reg & {nm}_en_reg);')
    if int_regs:
        ln()

    # --- RAM combinational assigns ---
    for r in ram_regs:
        name  = r['name'].lower()
        alen  = r['alen']
        dlen  = r['dlen']
        base  = f"ADDR_{r['name']}"
        if alen > 0 and (r['addr'] & ((1 << alen) - 1)) != 0:
            sys.exit(f"Error: register '{r['name']}' addr 0x{r['addr']:x} must be aligned to alen={alen} (low {alen} bits = 0)")
        if alen == 0:
            sel_cond = f"sab_addr == {base}"
        elif alen < addr_w:
            sel_cond = f"sab_addr[{addr_w-1}:{alen}] == {base}[{addr_w-1}:{alen}]"
        else:  # alen == addr_w
            sel_cond = "1'b1"
        ln(f'    assign {name}_sel  = {sel_cond};')
        if alen > 0:
            ln(f'    assign {name}_addr = sab_addr[{alen-1}:0];')
        if r['type'] in RAM_WRITES:
            ln(f'    assign {name}_wdata = sab_wdata[{dlen-1}:0];')
            # vld_pos_edge = 1-cycle pulse per SAB transaction; using sab_valid
            # directly would keep wen high across multi-cycle sab_valid, pushing
            # the same word into a FIFO multiple times.
            ln(f'    assign {name}_wen   = vld_pos_edge && sab_wen  && {name}_sel;')
        if r['type'] in RAM_READS:
            ln(f'    assign {name}_ren   = vld_pos_edge && !sab_wen && {name}_sel;')
        ln()

    # --- write always_ff ---
    if rw_wo_regs:
        ln('    always_ff @(posedge clk or negedge rst_n) begin')
        ln('        if (!rst_n) begin')
        for r, f, hi, lo, w in rw_wo_fields:
            ln(f'            {f["name"]}_reg <= {reset_literal(w, f.get("reset", 0))};')
        ln('        end else if (sab_valid && sab_wen) begin')
        ln('            case (sab_addr)')
        for r in rw_wo_regs:
            ln(f"                ADDR_{r['name']}: begin")
            for f in r['fields']:
                hi, lo, w = parse_bits(f['bits'])
                bits_ref = f'[{hi}]' if w == 1 else f'[{hi}:{lo}]'
                ln(f'                    {f["name"]}_reg <= sab_wdata{bits_ref};')
            ln('                end')
        ln('                default: ;')
        ln('            endcase')
        ln('        end')
        ln('    end')
        ln()

    # --- RC capture always_ff ---
    if rc_regs:
        ln('    always_ff @(posedge clk or negedge rst_n) begin')
        ln('        if (!rst_n) begin')
        for r in rc_regs:
            ln(f"            {r['name'].lower()}_rc_reg <= '0;")
        ln('        end else begin')
        for r in rc_regs:
            rc_reg = f"{r['name'].lower()}_rc_reg"
            ln(f"            if (vld_pos_edge && !sab_wen && sab_addr == ADDR_{r['name']})")
            ln(f'                {rc_reg} <= {r["src"]};  // clear but capture same-cycle pulse')
            ln(f'            else')
            ln(f'                {rc_reg} <= {rc_reg} | {r["src"]};')
        ln('        end')
        ln('    end')
        ln()

    # --- W1C capture always_ff ---
    if w1c_regs:
        ln('    always_ff @(posedge clk or negedge rst_n) begin')
        ln('        if (!rst_n) begin')
        for r in w1c_regs:
            ln(f"            {r['name'].lower()}_w1c_reg <= '0;")
        ln('        end else begin')
        for r in w1c_regs:
            sw = src_width(r)
            w1c_reg = f"{r['name'].lower()}_w1c_reg"
            ln(f"            if (vld_pos_edge && sab_wen && sab_addr == ADDR_{r['name']})")
            ln(f'                {w1c_reg} <= ({w1c_reg} & ~sab_wdata[{sw-1}:0]) | {r["src"]};  // W1C, capture same-cycle pulse')
            ln(f'            else')
            ln(f'                {w1c_reg} <= {w1c_reg} | {r["src"]};')
        ln('        end')
        ln('    end')
        ln()

    # --- INT pending (read-clear) + enable (RW) always_ff ---
    for r in int_regs:
        sw   = src_width(r)
        ireg = f"{r['name'].lower()}_int_reg"
        ereg = f"{r['name'].lower()}_en_reg"
        ln('    always_ff @(posedge clk or negedge rst_n) begin')
        ln('        if (!rst_n) begin')
        ln(f"            {ireg} <= '0;")
        ln('        end else begin')
        ln(f"            if (vld_pos_edge && !sab_wen && sab_addr == ADDR_{r['name']})")
        ln(f'                {ireg} <= {r["src"]};  // clear on read, capture same-cycle')
        ln('            else')
        ln(f'                {ireg} <= {ireg} | {r["src"]};')
        ln('        end')
        ln('    end')
        ln()
        ln('    always_ff @(posedge clk or negedge rst_n) begin')
        ln('        if (!rst_n) begin')
        ln(f"            {ereg} <= '0;")
        ln(f"        end else if (sab_valid && sab_wen && sab_addr == ADDR_{r['name']}_EN) begin")
        ln(f'            {ereg} <= sab_wdata[{sw-1}:0];')
        ln('        end')
        ln('    end')
        ln()

    # --- counter always_ff ---
    for r in cnt_regs:
        reg_name = f"{r['name'].lower()}_reg"
        ln(f'    always_ff @(posedge clk or negedge rst_n) begin')
        ln(f'        if (!rst_n) begin')
        ln(f"            {reg_name} <= '0;")
        if r['type'] == 'RC_CNT':
            ln(f"        end else if (vld_pos_edge && !sab_wen && sab_addr == ADDR_{r['name']}) begin")
            ln(f'            {reg_name} <= {r["src"]};  // clear but capture same-cycle inc')
        ln(f"        end else if ({r['src']}) begin")
        ln(f"            {reg_name} <= {reg_name} + 1'b1;")
        ln(f'        end')
        ln(f'    end')
        ln()

    # --- read always_ff ---
    ln('    always_ff @(posedge clk or negedge rst_n) begin')
    ln('        if (!rst_n) begin')
    ln("            sab_rdata <= '0;")
    ln('        end else begin')
    ln('            if (sab_valid && !sab_wen) begin')
    B = '                '  # 16-space base indent inside if(valid && !wen)
    ram_read_regs = [r for r in ram_regs if r['type'] in RAM_READS]
    for i, r in enumerate(ram_read_regs):
        name = r['name'].lower()
        kw   = 'if' if i == 0 else 'else if'
        expr = padded_src_expr(f'{name}_rdata', r['dlen'], data_w)
        ln(f'{B}{kw} ({name}_sel)')
        ln(f'{B}    sab_rdata <= {expr};')
    if ram_read_regs:
        ln(f'{B}else')
        C = B + '    '  # case block indented one more level
    else:
        C = B

    ln(f'{C}unique case (sab_addr)')
    for r in non_ram_regs:
        label = f"ADDR_{r['name']}:"
        rtype = r['type']
        if rtype == 'RW':
            expr = build_rdata_expr(r['fields'], data_w)
        elif rtype == 'WO':
            expr = "'0"
        elif rtype == 'RO':
            expr = padded_src_expr(r['src'], src_width(r), data_w)
        elif rtype == 'RC':
            rc_reg = f"{r['name'].lower()}_rc_reg"
            expr = padded_src_expr(rc_reg, src_width(r), data_w)
        elif rtype == 'W1C':
            expr = padded_src_expr(f"{r['name'].lower()}_w1c_reg", src_width(r), data_w)
        elif rtype == 'INT':
            expr = padded_src_expr(f"{r['name'].lower()}_int_reg", src_width(r), data_w)
        else:  # RO_CNT / RC_CNT
            cnt_reg = f"{r['name'].lower()}_reg"
            expr = padded_src_expr(cnt_reg, src_width(r), data_w)
        ln(f'{C}    {label:<16} sab_rdata <= {expr};')
        if rtype == 'INT':
            en_label = f"ADDR_{r['name']}_EN:"
            en_expr  = padded_src_expr(f"{r['name'].lower()}_en_reg", src_width(r), data_w)
            ln(f'{C}    {en_label:<16} sab_rdata <= {en_expr};')
    ln(f"{C}    default:         sab_rdata <= {data_w}'hdeadbeef;")
    ln(f'{C}endcase')
    ln('            end')
    ln('        end')
    ln('    end')
    ln()
    ln('endmodule')

    return '\n'.join(L)


def generate_addr_pkg(cfg):
    """Emit a companion SV package with SAB address constants + RAM geometry.

    Consumed by testbench / UVM RAL / any external agent that needs to talk to
    the cfg module without hard-coding magic numbers. YAML is the single source
    of truth; module.sv and *_addr_pkg.sv are generated together.
    """
    module = cfg['module']
    addr_w = cfg['addr_w']
    data_w = cfg['data_w']
    regs   = cfg['registers']

    RAM_TYPES = {'RAM_RW', 'RAM_RO', 'RAM_WO'}
    int_regs  = [r for r in regs if r['type'] == 'INT']
    ram_regs  = [r for r in regs if r['type'] in RAM_TYPES]

    L = []

    def ln(s=''):
        L.append(s)

    ln(f'// {module}_addr_pkg — generated by gen_cfg.py')
    ln('//')
    ln(f'// SAB address constants + RAM segment geometry for {module}.')
    ln('// tb / UVM RAL / external agents import this to avoid hard-coding addresses.')
    ln()
    ln(f'package {module}_addr_pkg;')
    ln(f'    localparam int ADDR_W = {addr_w};')
    ln(f'    localparam int DATA_W = {data_w};')
    ln()
    ln('    // ── Register addresses ────────────────────────────────')
    name_w = max((len(r['name']) for r in regs), default=0)
    if int_regs:
        name_w = max(name_w, max(len(r['name']) + 3 for r in int_regs))  # "_EN"
    for r in regs:
        ln(f"    localparam logic [ADDR_W-1:0] ADDR_{r['name']:<{name_w}} = {addr_w}'h{r['addr']:x};")
    for r in int_regs:
        en_name = r['name'] + '_EN'
        ln(f"    localparam logic [ADDR_W-1:0] ADDR_{en_name:<{name_w}} = {addr_w}'h{r['enable_addr']:x};")

    if ram_regs:
        ln()
        ln('    // ── RAM segment geometry ──────────────────────────────')
        for r in ram_regs:
            ln(f"    localparam int {r['name']}_ALEN = {r['alen']};")
            ln(f"    localparam int {r['name']}_DLEN = {r['dlen']};")

    ln('endpackage')
    return '\n'.join(L) + '\n'


def generate_ral(cfg):
    """Emit a UVM RAL model: one uvm_reg subclass per non-RAM register plus a
    <module>_reg_block that owns default_map + all mem windows.

    Requires the companion <module>_addr_pkg (also generated) to be imported
    so that add_reg / add_mem can reference ADDR_<NAME> constants by symbol.
    """
    module = cfg['module']
    addr_w = cfg['addr_w']
    data_w = cfg['data_w']
    regs   = cfg['registers']

    RAM_TYPES  = {'RAM_RW', 'RAM_RO', 'RAM_WO'}
    # uvm_mem 只支持 RW / RO (uvm_mem.svh:970). RAM_WO 映射到 RW —
    # 硬件 write-only 由 tb 约定不去读, UVM 层放宽避免 elab error.
    RAM_ACCESS = {'RAM_RW': 'RW', 'RAM_RO': 'RO', 'RAM_WO': 'RW'}

    # yaml type → (uvm field access, is_rand, add_reg rights)
    #   is_rand=0 for RO / RC / W1C / *_CNT / INT (side-effect or read-only, no random write)
    #   add_reg rights uses the closest UVM-legal access string
    TYPE_MAP = {
        'RW':     ('RW',  1, 'RW'),
        'WO':     ('WO',  1, 'WO'),
        'RO':     ('RO',  0, 'RO'),
        'RC':     ('RC',  0, 'RW'),
        'W1C':    ('W1C', 0, 'RW'),
        'RO_CNT': ('RO',  0, 'RO'),
        'RC_CNT': ('RC',  0, 'RW'),
        'INT':    ('RW',  0, 'RW'),   # simplified; enable_addr not modeled
    }

    non_ram_regs = [r for r in regs if r['type'] not in RAM_TYPES]
    ram_regs     = [r for r in regs if r['type'] in RAM_TYPES]

    L = []

    def ln(s=''):
        L.append(s)

    guard = f'{module.upper()}_RAL_SV'
    ln(f'// {module}_ral — generated by gen_cfg.py')
    ln('//')
    ln(f'// UVM RAL model for {module}. One uvm_reg subclass per non-RAM register,')
    ln(f'// plus {module}_reg_block owning default_map + uvm_mem windows.')
    ln(f'// Depends on {module}_addr_pkg (imported by consumer for ADDR_* constants).')
    ln()
    ln(f'`ifndef {guard}')
    ln(f'`define {guard}')
    ln()

    # ── uvm_reg subclasses ────────────────────────────────
    for r in non_ram_regs:
        cls_name  = f'{r["name"].lower()}_reg'
        field_ac, is_rand, _ = TYPE_MAP.get(r['type'], ('RW', 1, 'RW'))
        rand_kw = 'rand ' if is_rand else ''

        ln(f'class {cls_name} extends uvm_reg;')
        for f in r['fields']:
            ln(f'    {rand_kw}uvm_reg_field {f["name"]};')
        ln(f'    `uvm_object_utils({cls_name})')
        ln()
        ln(f'    function new(string name = "{cls_name}");')
        ln(f'        super.new(name, {data_w}, UVM_NO_COVERAGE);')
        ln('    endfunction')
        ln()
        ln('    virtual function void build();')
        for f in r['fields']:
            _, lo, w = parse_bits(f['bits'])
            reset_val = f.get('reset', 0)
            has_reset = 1 if is_rand else 0
            ln(f'        {f["name"]} = uvm_reg_field::type_id::create("{f["name"]}");')
            # configure(parent, size, lsb_pos, access, volatile, reset, has_reset, is_rand, individually_accessible)
            ln(f'        {f["name"]}.configure(this, {w}, {lo}, "{field_ac}", 0, {reset_val}, {has_reset}, {is_rand}, 1);')
        ln('    endfunction')
        ln(f'endclass : {cls_name}')
        ln()

    # ── reg_block ─────────────────────────────────────────
    block_name = f'{module}_reg_block'
    ln(f'class {block_name} extends uvm_reg_block;')
    for r in non_ram_regs:
        cls_name  = f'{r["name"].lower()}_reg'
        _, is_rand, _ = TYPE_MAP.get(r['type'], ('RW', 1, 'RW'))
        rand_kw = 'rand ' if is_rand else ''
        ln(f'    {rand_kw}{cls_name} {r["name"]};')
    for r in ram_regs:
        ln(f'    uvm_mem {r["name"]};')
    ln(f'    `uvm_object_utils({block_name})')
    ln()
    ln(f'    function new(string name = "{block_name}");')
    ln('        super.new(name, UVM_NO_COVERAGE);')
    ln('    endfunction')
    ln()
    ln('    virtual function void build();')
    if non_ram_regs:
        ln('        // ── create + configure + build each uvm_reg ──')
        for r in non_ram_regs:
            cls_name = f'{r["name"].lower()}_reg'
            ln(f'        {r["name"]} = {cls_name}::type_id::create("{r["name"]}");')
            ln(f'        {r["name"]}.configure(this, null, "");')
            ln(f'        {r["name"]}.build();')

    if ram_regs:
        ln()
        ln('        // ── new() each uvm_mem (base class not registered with factory), ')
        ln('        //    then configure() to attach it as a child of this block. ──')
        for r in ram_regs:
            size   = 1 << r['alen']
            n_bits = r['dlen']
            access = RAM_ACCESS[r['type']]
            ln(f'        {r["name"]} = new("{r["name"]}", {size}, {n_bits}, "{access}", UVM_NO_COVERAGE);')
            ln(f'        {r["name"]}.configure(this, "");')

    n_bytes = data_w // 8
    ln()
    ln('        // ── default_map ─────────────────────────────')
    ln('        default_map = create_map(')
    ln('            .name           ("default_map"),')
    ln(f'            .base_addr      ({addr_w}\'h0),')
    ln(f'            .n_bytes        ({n_bytes}),')
    ln('            .endian         (UVM_LITTLE_ENDIAN),')
    ln('            .byte_addressing(0)')
    ln('        );')

    ln()
    ln('        // ── add_reg / add_mem (地址从 ' + module + '_addr_pkg::ADDR_* 拿) ──')
    for r in non_ram_regs:
        _, _, rights = TYPE_MAP.get(r['type'], ('RW', 1, 'RW'))
        ln(f'        default_map.add_reg({r["name"]}, {module}_addr_pkg::ADDR_{r["name"]}, "{rights}");')
    for r in ram_regs:
        access = RAM_ACCESS[r['type']]
        ln(f'        default_map.add_mem({r["name"]}, {module}_addr_pkg::ADDR_{r["name"]}, "{access}");')

    ln()
    ln('        lock_model();')
    ln('    endfunction')
    ln(f'endclass : {block_name}')
    ln()
    ln(f'`endif // {guard}')

    return '\n'.join(L) + '\n'


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    yaml_path = Path(sys.argv[1])
    with open(yaml_path) as f:
        cfg = yaml.safe_load(f)

    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else yaml_path.with_suffix('.sv')
    out_path.write_text(generate(cfg))
    print(f'Generated: {out_path}')

    pkg_path = out_path.parent / f"{cfg['module']}_addr_pkg.sv"
    pkg_path.write_text(generate_addr_pkg(cfg))
    print(f'Generated: {pkg_path}')

    ral_path = out_path.parent / f"{cfg['module']}_ral.sv"
    ral_path.write_text(generate_ral(cfg))
    print(f'Generated: {ral_path}')


if __name__ == '__main__':
    main()
