`ifndef RAL_ALL_REGS_TEST_SV
`define RAL_ALL_REGS_TEST_SV

// ral_all_regs_test — validate the full RAL pathway generated by gen_cfg.py.
//
// Coverage:
//   - 6 RW regs (write pattern → read back → compare)
//   - 1 RO reg  (STATUS) can be read
//   - 3 uvm_mem windows (ABUF/WFIFO write, ACCUM read)
//
// No TPU execution — this is a wiring / adapter / addr sanity check only.
// ACCUM: sdpram reset value is implementation-defined, so we only check
// that the read handshake completes (status == UVM_IS_OK).

class ral_all_regs_test extends sab_base_test;
    `uvm_component_utils(ral_all_regs_test)

    function new (string name = "ral_all_regs_test", uvm_component parent = null);
        super.new(name, parent);
    endfunction

    task run_phase(uvm_phase phase);
        uvm_status_e   status;
        uvm_reg_data_t rdata;
        int errors;

        phase.raise_objection(this);
        `uvm_info(get_type_name(), "ral all-regs test start", UVM_LOW)

        #200;   // wait for hw rst
        errors = 0;

        // ── RW regs: write pattern → read back → compare ──────────────────
        // START (1-bit)
        u_env.reg_model.START.write(status, 32'd1);
        u_env.reg_model.START.read (status, rdata);
        if (rdata[0] !== 1'b1) begin
            errors++;
            `uvm_error(get_type_name(),
                $sformatf("START readback: got %0b, expected 1", rdata[0]))
        end
        // clear so a downstream test can fire a fresh pulse
        u_env.reg_model.START.write(status, 32'd0);

        // ACTIV_AVAIL (1-bit)
        u_env.reg_model.ACTIV_AVAIL.write(status, 32'd1);
        u_env.reg_model.ACTIV_AVAIL.read (status, rdata);
        if (rdata[0] !== 1'b1) begin
            errors++;
            `uvm_error(get_type_name(),
                $sformatf("ACTIV_AVAIL readback: got %0b, expected 1", rdata[0]))
        end
        u_env.reg_model.ACTIV_AVAIL.write(status, 32'd0);

        // WTILE_NUM (3-bit): value 5
        u_env.reg_model.WTILE_NUM.write(status, 32'd5);
        u_env.reg_model.WTILE_NUM.read (status, rdata);
        if (rdata[2:0] !== 3'd5) begin
            errors++;
            `uvm_error(get_type_name(),
                $sformatf("WTILE_NUM readback: got %0d, expected 5", rdata[2:0]))
        end

        // ACT_STADDR (8-bit): value 0xA5
        u_env.reg_model.ACT_STADDR.write(status, 32'hA5);
        u_env.reg_model.ACT_STADDR.read (status, rdata);
        if (rdata[7:0] !== 8'hA5) begin
            errors++;
            `uvm_error(get_type_name(),
                $sformatf("ACT_STADDR readback: got 0x%0h, expected 0xA5", rdata[7:0]))
        end

        // ACC_STADDR (10-bit): value 0x3AB
        u_env.reg_model.ACC_STADDR.write(status, 32'h3AB);
        u_env.reg_model.ACC_STADDR.read (status, rdata);
        if (rdata[9:0] !== 10'h3AB) begin
            errors++;
            `uvm_error(get_type_name(),
                $sformatf("ACC_STADDR readback: got 0x%0h, expected 0x3AB", rdata[9:0]))
        end

        // FEED_NUM (9-bit): value 0x123
        u_env.reg_model.FEED_NUM.write(status, 32'h123);
        u_env.reg_model.FEED_NUM.read (status, rdata);
        if (rdata[8:0] !== 9'h123) begin
            errors++;
            `uvm_error(get_type_name(),
                $sformatf("FEED_NUM readback: got 0x%0h, expected 0x123", rdata[8:0]))
        end

        // ── STATUS (RO): print current value ──────────────────────────────
        u_env.reg_model.STATUS.read(status, rdata);
        `uvm_info(get_type_name(),
            $sformatf("STATUS = 0x%0h (ws_state=%0d wfifo_full=%0b)",
                      rdata, rdata[2:0], rdata[3]), UVM_LOW)

        // ── WFIFO (RAM_WO): 灌几字节 ──────────────────────────────────────
        // uvm_mem offset = element index. WFIFO size=8, N=2 → cols 0..1.
        for (int c = 0; c < 2; c++) begin
            for (int i = 0; i < 3; i++) begin
                u_env.reg_model.WFIFO.write(status, c, 8'(c * 16 + i));
                if (status != UVM_IS_OK) begin
                    errors++;
                    `uvm_error(get_type_name(),
                        $sformatf("WFIFO write col=%0d iter=%0d failed", c, i))
                end
            end
        end

        // ── ABUF (RAM_WO): 灌 2 行 × 4 字节 ────────────────────────────────
        // ABUF offset layout: [10:8]=row, [7:0]=byte
        for (int r = 0; r < 2; r++) begin
            for (int b = 0; b < 4; b++) begin
                u_env.reg_model.ABUF.write(status, (r << 8) | b, 8'(r * 10 + b));
                if (status != UVM_IS_OK) begin
                    errors++;
                    `uvm_error(get_type_name(),
                        $sformatf("ABUF write row=%0d byte=%0d failed", r, b))
                end
            end
        end

        // ── ACCUM (RAM_RO): 只验证 SAB read 握手成功, 不检查数据值 ─────────
        // ACCUM offset layout: [12:10]=col, [9:0]=row.
        // sdpram reset value 实现相关, 值本身不可靠.
        for (int c = 0; c < 2; c++) begin
            for (int r = 0; r < 4; r++) begin
                u_env.reg_model.ACCUM.read(status, (c << 10) | r, rdata);
                if (status != UVM_IS_OK) begin
                    errors++;
                    `uvm_error(get_type_name(),
                        $sformatf("ACCUM read col=%0d row=%0d failed", c, r))
                end
                `uvm_info(get_type_name(),
                    $sformatf("ACCUM[c=%0d r=%0d] = 0x%0h", c, r, rdata), UVM_HIGH)
            end
        end

        if (errors == 0)
            `uvm_info(get_type_name(),
                "ALL 6 regs + STATUS + 3 mems: PASS", UVM_LOW)
        else
            `uvm_error(get_type_name(),
                $sformatf("total %0d mismatches", errors))

        `uvm_info(get_type_name(), "ral all-regs test done", UVM_LOW)
        phase.drop_objection(this);
    endtask
endclass

`endif // RAL_ALL_REGS_TEST_SV