// satpu_cfg_addr_pkg — generated by gen_cfg.py
//
// SAB address constants + RAM segment geometry for satpu_cfg.
// tb / UVM RAL / external agents import this to avoid hard-coding addresses.

package satpu_cfg_addr_pkg;
    localparam int ADDR_W = 16;
    localparam int DATA_W = 32;

    // ── Register addresses ────────────────────────────────
    localparam logic [ADDR_W-1:0] ADDR_START       = 16'h0;
    localparam logic [ADDR_W-1:0] ADDR_ACTIV_AVAIL = 16'h1;
    localparam logic [ADDR_W-1:0] ADDR_WTILE_NUM   = 16'h2;
    localparam logic [ADDR_W-1:0] ADDR_ACT_STADDR  = 16'h3;
    localparam logic [ADDR_W-1:0] ADDR_ACC_STADDR  = 16'h4;
    localparam logic [ADDR_W-1:0] ADDR_FEED_NUM    = 16'h5;
    localparam logic [ADDR_W-1:0] ADDR_STATUS      = 16'h6;
    localparam logic [ADDR_W-1:0] ADDR_WFIFO       = 16'h10;
    localparam logic [ADDR_W-1:0] ADDR_ACCUM       = 16'h2000;
    localparam logic [ADDR_W-1:0] ADDR_ABUF        = 16'h4000;

    // ── RAM segment geometry ──────────────────────────────
    localparam int WFIFO_ALEN = 3;
    localparam int WFIFO_DLEN = 8;
    localparam int ACCUM_ALEN = 13;
    localparam int ACCUM_DLEN = 32;
    localparam int ABUF_ALEN = 14;
    localparam int ABUF_DLEN = 8;
endpackage
