// satpu_cfg — generated by gen_cfg.py

module satpu_cfg #(
    parameter int ADDR_W = 16,
    parameter int DATA_W = 32
) (
    input  logic                clk,
    input  logic                rst_n,

    input  logic                sab_valid,
    input  logic                sab_wen,
    input  logic [ADDR_W-1:0]   sab_addr,
    input  logic [DATA_W-1:0]   sab_wdata,
    output logic                sab_ready,
    output logic [DATA_W-1:0]   sab_rdata,

    output logic                start,
    output logic                activ_avail,
    output logic [7:0]          wtile_num,
    output logic [10:0]         act_staddr,
    output logic [9:0]          acc_staddr,
    output logic [11:0]         feed_num,
    input  logic [3:0]          tpu_status,
    output logic [2:0]          wfifo_addr,
    output logic [7:0]          wfifo_wdata,
    output logic                wfifo_wen,
    output logic [12:0]         accum_addr,
    input  logic [31:0]         accum_rdata,
    output logic                accum_ren,
    output logic [13:0]         abuf_addr,
    output logic [7:0]          abuf_wdata,
    output logic                abuf_wen
);

    localparam logic [ADDR_W-1:0] ADDR_START      = 16'h0;
    localparam logic [ADDR_W-1:0] ADDR_ACTIV_AVAIL = 16'h1;
    localparam logic [ADDR_W-1:0] ADDR_WTILE_NUM  = 16'h2;
    localparam logic [ADDR_W-1:0] ADDR_ACT_STADDR = 16'h3;
    localparam logic [ADDR_W-1:0] ADDR_ACC_STADDR = 16'h4;
    localparam logic [ADDR_W-1:0] ADDR_FEED_NUM   = 16'h5;
    localparam logic [ADDR_W-1:0] ADDR_STATUS     = 16'h6;
    localparam logic [ADDR_W-1:0] ADDR_WFIFO      = 16'h10;
    localparam logic [ADDR_W-1:0] ADDR_ACCUM      = 16'h2000;
    localparam logic [ADDR_W-1:0] ADDR_ABUF       = 16'h4000;

    logic start_reg;
    logic activ_avail_reg;
    logic [7:0] wtile_num_reg;
    logic [10:0] act_staddr_reg;
    logic [9:0] acc_staddr_reg;
    logic [11:0] feed_num_reg;
    logic wfifo_sel;
    logic accum_sel;
    logic abuf_sel;

    logic sab_valid_d;
    logic vld_pos_edge;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sab_valid_d <= 1'b0;
        end else begin
            sab_valid_d <= sab_valid;
        end
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sab_ready <= 1'b0;
        end else begin
            sab_ready <= vld_pos_edge;
        end
    end

    assign vld_pos_edge = sab_valid & ~sab_valid_d;

    assign start = start_reg;
    assign activ_avail = activ_avail_reg;
    assign wtile_num = wtile_num_reg;
    assign act_staddr = act_staddr_reg;
    assign acc_staddr = acc_staddr_reg;
    assign feed_num = feed_num_reg;

    assign wfifo_sel  = sab_addr[15:3] == ADDR_WFIFO[15:3];
    assign wfifo_addr = sab_addr[2:0];
    assign wfifo_wdata = sab_wdata[7:0];
    assign wfifo_wen   = vld_pos_edge && sab_wen  && wfifo_sel;

    assign accum_sel  = sab_addr[15:13] == ADDR_ACCUM[15:13];
    assign accum_addr = sab_addr[12:0];
    assign accum_ren   = vld_pos_edge && !sab_wen && accum_sel;

    assign abuf_sel  = sab_addr[15:14] == ADDR_ABUF[15:14];
    assign abuf_addr = sab_addr[13:0];
    assign abuf_wdata = sab_wdata[7:0];
    assign abuf_wen   = vld_pos_edge && sab_wen  && abuf_sel;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            start_reg <= 1'b0;
            activ_avail_reg <= 1'b0;
            wtile_num_reg <= 8'd0;
            act_staddr_reg <= 11'd0;
            acc_staddr_reg <= 10'd0;
            feed_num_reg <= 12'd0;
        end else if (sab_valid && sab_wen) begin
            case (sab_addr)
                ADDR_START: begin
                    start_reg <= sab_wdata[0];
                end
                ADDR_ACTIV_AVAIL: begin
                    activ_avail_reg <= sab_wdata[0];
                end
                ADDR_WTILE_NUM: begin
                    wtile_num_reg <= sab_wdata[7:0];
                end
                ADDR_ACT_STADDR: begin
                    act_staddr_reg <= sab_wdata[10:0];
                end
                ADDR_ACC_STADDR: begin
                    acc_staddr_reg <= sab_wdata[9:0];
                end
                ADDR_FEED_NUM: begin
                    feed_num_reg <= sab_wdata[11:0];
                end
                default: ;
            endcase
        end
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sab_rdata <= '0;
        end else begin
            if (sab_valid && !sab_wen) begin
                if (accum_sel)
                    sab_rdata <= accum_rdata;
                else
                    unique case (sab_addr)
                        ADDR_START:      sab_rdata <= {31'b0, start_reg};
                        ADDR_ACTIV_AVAIL: sab_rdata <= {31'b0, activ_avail_reg};
                        ADDR_WTILE_NUM:  sab_rdata <= {24'b0, wtile_num_reg};
                        ADDR_ACT_STADDR: sab_rdata <= {21'b0, act_staddr_reg};
                        ADDR_ACC_STADDR: sab_rdata <= {22'b0, acc_staddr_reg};
                        ADDR_FEED_NUM:   sab_rdata <= {20'b0, feed_num_reg};
                        ADDR_STATUS:     sab_rdata <= {28'b0, tpu_status};
                        default:         sab_rdata <= 32'hdeadbeef;
                    endcase
            end
        end
    end

endmodule