// satpu_cfg_ral — generated by gen_cfg.py
//
// UVM RAL model for satpu_cfg. One uvm_reg subclass per non-RAM register,
// plus satpu_cfg_reg_block owning default_map + uvm_mem windows.
// Depends on satpu_cfg_addr_pkg (imported by consumer for ADDR_* constants).

`ifndef SATPU_CFG_RAL_SV
`define SATPU_CFG_RAL_SV

class start_reg extends uvm_reg;
    rand uvm_reg_field start;
    `uvm_object_utils(start_reg)

    function new(string name = "start_reg");
        super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
        start = uvm_reg_field::type_id::create("start");
        start.configure(this, 1, 0, "RW", 0, 0, 1, 1, 1);
    endfunction
endclass : start_reg

class activ_avail_reg extends uvm_reg;
    rand uvm_reg_field activ_avail;
    `uvm_object_utils(activ_avail_reg)

    function new(string name = "activ_avail_reg");
        super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
        activ_avail = uvm_reg_field::type_id::create("activ_avail");
        activ_avail.configure(this, 1, 0, "RW", 0, 0, 1, 1, 1);
    endfunction
endclass : activ_avail_reg

class wtile_num_reg extends uvm_reg;
    rand uvm_reg_field wtile_num;
    `uvm_object_utils(wtile_num_reg)

    function new(string name = "wtile_num_reg");
        super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
        wtile_num = uvm_reg_field::type_id::create("wtile_num");
        wtile_num.configure(this, 8, 0, "RW", 0, 0, 1, 1, 1);
    endfunction
endclass : wtile_num_reg

class act_staddr_reg extends uvm_reg;
    rand uvm_reg_field act_staddr;
    `uvm_object_utils(act_staddr_reg)

    function new(string name = "act_staddr_reg");
        super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
        act_staddr = uvm_reg_field::type_id::create("act_staddr");
        act_staddr.configure(this, 11, 0, "RW", 0, 0, 1, 1, 1);
    endfunction
endclass : act_staddr_reg

class acc_staddr_reg extends uvm_reg;
    rand uvm_reg_field acc_staddr;
    `uvm_object_utils(acc_staddr_reg)

    function new(string name = "acc_staddr_reg");
        super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
        acc_staddr = uvm_reg_field::type_id::create("acc_staddr");
        acc_staddr.configure(this, 10, 0, "RW", 0, 0, 1, 1, 1);
    endfunction
endclass : acc_staddr_reg

class feed_num_reg extends uvm_reg;
    rand uvm_reg_field feed_num;
    `uvm_object_utils(feed_num_reg)

    function new(string name = "feed_num_reg");
        super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
        feed_num = uvm_reg_field::type_id::create("feed_num");
        feed_num.configure(this, 12, 0, "RW", 0, 0, 1, 1, 1);
    endfunction
endclass : feed_num_reg

class status_reg extends uvm_reg;
    uvm_reg_field ws_state;
    uvm_reg_field wfifo_full;
    `uvm_object_utils(status_reg)

    function new(string name = "status_reg");
        super.new(name, 32, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
        ws_state = uvm_reg_field::type_id::create("ws_state");
        ws_state.configure(this, 3, 0, "RO", 0, 0, 0, 0, 1);
        wfifo_full = uvm_reg_field::type_id::create("wfifo_full");
        wfifo_full.configure(this, 1, 3, "RO", 0, 0, 0, 0, 1);
    endfunction
endclass : status_reg

class satpu_cfg_reg_block extends uvm_reg_block;
    rand start_reg START;
    rand activ_avail_reg ACTIV_AVAIL;
    rand wtile_num_reg WTILE_NUM;
    rand act_staddr_reg ACT_STADDR;
    rand acc_staddr_reg ACC_STADDR;
    rand feed_num_reg FEED_NUM;
    status_reg STATUS;
    uvm_mem WFIFO;
    uvm_mem ACCUM;
    uvm_mem ABUF;
    `uvm_object_utils(satpu_cfg_reg_block)

    function new(string name = "satpu_cfg_reg_block");
        super.new(name, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
        // ── create + configure + build each uvm_reg ──
        START = start_reg::type_id::create("START");
        START.configure(this, null, "");
        START.build();
        ACTIV_AVAIL = activ_avail_reg::type_id::create("ACTIV_AVAIL");
        ACTIV_AVAIL.configure(this, null, "");
        ACTIV_AVAIL.build();
        WTILE_NUM = wtile_num_reg::type_id::create("WTILE_NUM");
        WTILE_NUM.configure(this, null, "");
        WTILE_NUM.build();
        ACT_STADDR = act_staddr_reg::type_id::create("ACT_STADDR");
        ACT_STADDR.configure(this, null, "");
        ACT_STADDR.build();
        ACC_STADDR = acc_staddr_reg::type_id::create("ACC_STADDR");
        ACC_STADDR.configure(this, null, "");
        ACC_STADDR.build();
        FEED_NUM = feed_num_reg::type_id::create("FEED_NUM");
        FEED_NUM.configure(this, null, "");
        FEED_NUM.build();
        STATUS = status_reg::type_id::create("STATUS");
        STATUS.configure(this, null, "");
        STATUS.build();

        // ── new() each uvm_mem (base class not registered with factory), 
        //    then configure() to attach it as a child of this block. ──
        WFIFO = new("WFIFO", 8, 8, "RW", UVM_NO_COVERAGE);
        WFIFO.configure(this, "");
        ACCUM = new("ACCUM", 8192, 32, "RO", UVM_NO_COVERAGE);
        ACCUM.configure(this, "");
        ABUF = new("ABUF", 16384, 8, "RW", UVM_NO_COVERAGE);
        ABUF.configure(this, "");

        // ── default_map ─────────────────────────────
        default_map = create_map(
            .name           ("default_map"),
            .base_addr      (16'h0),
            .n_bytes        (4),
            .endian         (UVM_LITTLE_ENDIAN),
            .byte_addressing(0)
        );

        // ── add_reg / add_mem (地址从 satpu_cfg_addr_pkg::ADDR_* 拿) ──
        default_map.add_reg(START, satpu_cfg_addr_pkg::ADDR_START, "RW");
        default_map.add_reg(ACTIV_AVAIL, satpu_cfg_addr_pkg::ADDR_ACTIV_AVAIL, "RW");
        default_map.add_reg(WTILE_NUM, satpu_cfg_addr_pkg::ADDR_WTILE_NUM, "RW");
        default_map.add_reg(ACT_STADDR, satpu_cfg_addr_pkg::ADDR_ACT_STADDR, "RW");
        default_map.add_reg(ACC_STADDR, satpu_cfg_addr_pkg::ADDR_ACC_STADDR, "RW");
        default_map.add_reg(FEED_NUM, satpu_cfg_addr_pkg::ADDR_FEED_NUM, "RW");
        default_map.add_reg(STATUS, satpu_cfg_addr_pkg::ADDR_STATUS, "RO");
        default_map.add_mem(WFIFO, satpu_cfg_addr_pkg::ADDR_WFIFO, "RW");
        default_map.add_mem(ACCUM, satpu_cfg_addr_pkg::ADDR_ACCUM, "RO");
        default_map.add_mem(ABUF, satpu_cfg_addr_pkg::ADDR_ABUF, "RW");

        lock_model();
    endfunction
endclass : satpu_cfg_reg_block

`endif // SATPU_CFG_RAL_SV
